# Generated by Django 6.1.1 on 2026-10-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(
                choices=[
                    ('deportes', 'Deportes'),
                    ('comida', 'Comida'),
                    ('desarrollo web', 'Desarrollo web'),
                    ('gaming', 'Gaming'),
                ],
                default='desarrollo web',
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(
                choices=[
                    ('deportes', 'Deportes'),
                    ('comida', 'Comida'),
                    ('desarrollo web', 'Desarrollo web'),
                    ('gaming', 'Gaming'),
                ],
                max_length=30,
            ),
        ),
    ]
